// 等价于 import Button from "./Button.vue";export default Button
import "./useMath.scss"
export { default as UuButton } from './Button/Button.vue'
export { default as UuButtonGroup } from './Button/ButtonGroup.vue'
export { default as UuAside } from './container/Aside.vue'
export { default as UuContainer } from './container/Container.vue'
export { default as UuFooter } from './container/Footer.vue'
export { default as UuHeader } from './container/Header.vue'
export { default as UuMain } from './container/Main.vue'
export { openUuDialog } from './Dialog/openDialog'
export { default as UuDialog } from './Dialog/Dialog.vue'
export { default as UuCol } from './layout/col.vue'
export { default as UuRow } from './layout/row.vue'
export { default as UuMessage } from './Message/Message.vue'
export { openUuMessage } from './Message/openMessage'
export { default as UuInput } from './Input.vue'
export { default as UuSwitch } from './Switch.vue'
export { default as UuTabs } from './Tabs.vue'
export { default as UuTab } from './Tab.vue'
